
-- Migration: 001_create_hotel_schema.sql
-- This migration creates the hotel schema, tables, constraints and COPY statements
-- NOTE: The original SQL uses PostgreSQL features (schema, extensions, daterange, EXCLUDE USING gist).
-- Make sure your `database_url` in `sqlpage/sqlpage.json` points to a compatible Postgres instance
-- before running these migrations. SQLPage will run migrations against the configured DB.

-- 1. ELIMINAR Y CREAR SCHEMA
DROP SCHEMA public CASCADE;
CREATE SCHEMA public;

CREATE EXTENSION IF NOT EXISTS btree_gist;

---
--2. Crear Todas las Tablas (Solo Estructura, Sin Foreign Keys)

CREATE TABLE Area (
    IdArea integer GENERATED BY DEFAULT AS IDENTITY,
    NombreArea varchar(255) NOT NULL UNIQUE,
    PRIMARY KEY (IdArea)
);

CREATE TABLE Empleado (
    Cedula varchar(10) NOT NULL UNIQUE,
    PrimerNombre varchar(255) NOT NULL,
    SegundoNombre varchar(255),
    PrimerApellido varchar(255) NOT NULL,
    SegundoApellido varchar(255),
    Calle varchar(255) NOT NULL,
    Carrera varchar(255) NOT NULL,
    Numero varchar(255) NOT NULL,
    Complemento varchar(255) NOT NULL,
    Cargo varchar(255) NOT NULL,
    Area integer NOT NULL,
    Salario integer NOT NULL,
    PRIMARY KEY (Cedula),
    CONSTRAINT empleado_cedula_fmt CHECK (Cedula ~ '^[0-9]{8,10}$')
);

CREATE TABLE Cliente (
    Cedula varchar(10) NOT NULL UNIQUE,
    PrimerNombre varchar(255) NOT NULL,
    SegundoNombre varchar(255),
    PrimerApellido varchar(255) NOT NULL,
    SegundoApellido varchar(255),
    Calle varchar(255) NOT NULL,
    Carrera varchar(255) NOT NULL,
    Numero varchar(255) NOT NULL,
    Complemento varchar(255) NOT NULL,
    PRIMARY KEY (Cedula),
    CONSTRAINT cliente_cedula_fmt CHECK (Cedula ~ '^[0-9]{8,10}$')
);

CREATE TABLE TelefonoEmpleado (
    Cedula varchar(10) NOT NULL,
    Telefono bigint NOT NULL,
    PRIMARY KEY (Cedula, Telefono)
);

CREATE TABLE TelefonoCliente (
    Cedula varchar(10) NOT NULL,
    Telefono bigint NOT NULL,
    PRIMARY KEY (Cedula, Telefono)
);

CREATE TABLE CorreoCliente (
    Cedula varchar(10) NOT NULL,
    Correo varchar(320) NOT NULL,
    PRIMARY KEY (Cedula, Correo)
);

CREATE TABLE Habitacion (
    NumeroHabitacion bigint NOT NULL UNIQUE,
    Tipo varchar(255) NOT NULL,
    Precio DECIMAL(10,2) NOT NULL,
    Disponibilidad boolean NOT NULL,
    PRIMARY KEY (NumeroHabitacion),
    CONSTRAINT habitacion_precio_no_neg CHECK (Precio >= 0),
	CONSTRAINT habitacion_tipo_ck CHECK (Tipo in ('Sencilla','Doble','Suite'))
);

CREATE TABLE Servicio (
	IdServicio integer GENERATED BY DEFAULT AS IDENTITY,
    NombreServicio varchar(255) NOT NULL UNIQUE,
    Descripcion varchar(255) NOT NULL,
    Costo DECIMAL(10,2) NOT NULL,
    PRIMARY KEY (IdServicio),
    CONSTRAINT servicio_costo_no_neg CHECK (Costo >= 0)
);

CREATE TABLE Reservar (
    IdReserva bigint GENERATED BY DEFAULT AS IDENTITY,
    TiempoCancelacion bigint NOT NULL,
    FechaLlegada date NOT NULL,
    FechaSalida date NOT NULL,
    Cedula varchar(10) NOT NULL,
    NumeroHabitacion bigint NOT NULL,
    fecha_rango daterange GENERATED ALWAYS AS (daterange(FechaLlegada,FechaSalida,'[)')) STORED,
    PRIMARY KEY (IdReserva),
    CONSTRAINT reservar_fechas_check CHECK (FechaSalida > FechaLlegada)
);

CREATE TABLE Solicitar (
    Nombre varchar(255) NOT NULL,
    Fecha date NOT NULL,
    Hora time without time zone NOT NULL,
	IdServicio integer NOT NULL,
    IdReserva bigint NOT NULL,
	Cedula varchar(10) NOT NULL,
    PRIMARY KEY (Nombre, Fecha, Hora)
);

-- TABLA DE AUDITORÍA
CREATE TABLE Empleado_audit (
    id             SERIAL PRIMARY KEY,
    operacion      CHAR(1)      NOT NULL,
    usuario        TEXT         NOT NULL,
    ts             TIMESTAMPTZ  DEFAULT now(),
    cedula_empleado varchar(10),
    dato_viejo     JSONB,
    dato_nuevo     JSONB
);



---
--3. Carga de Datos

-- cuando se necesiten datos de prueba usamos csv descomentar
-- if your database server cannot access these paths.
--COPY Area (NombreArea) FROM 'C:\\DatosDePruebaHotel\\Area.csv' DELIMITER ',' CSV HEADER;
--COPY Empleado FROM 'C:\\DatosDePruebaHotel\\Empleado.csv' DELIMITER ',' CSV HEADER;
--COPY Cliente FROM 'C:\\DatosDePruebaHotel\\Cliente.csv' DELIMITER ',' CSV HEADER;
--COPY TelefonoEmpleado FROM 'C:\\DatosDePruebaHotel\\TelefonoEmpleado.csv' DELIMITER ',' CSV HEADER;
--COPY TelefonoCliente FROM 'C:\\DatosDePruebaHotel\\TelefonoCliente.csv' DELIMITER ',' CSV HEADER;
--COPY CorreoCliente FROM 'C:\\DatosDePruebaHotel\\CorreoCliente.csv' DELIMITER ',' CSV HEADER;
--COPY Habitacion FROM 'C:\\DatosDePruebaHotel\\Habitacion.csv' DELIMITER ',' CSV HEADER;
--COPY Servicio (NombreServicio, Descripcion, Costo) FROM 'C:\\DatosDePruebaHotel\\Servicio.csv' DELIMITER ',' CSV HEADER;
--COPY Reservar FROM 'C:\\DatosDePruebaHotel\\Reservar.csv' DELIMITER ',' CSV HEADER;
--COPY Solicitar FROM 'C:\\DatosDePruebaHotel\\Solicitar.csv' DELIMITER ',' CSV HEADER;


---
-- 4. Adición de Foreign Keys y Constraints

ALTER TABLE Empleado ADD CONSTRAINT Empleado_fk0 FOREIGN KEY (Area) REFERENCES Area(IdArea);
ALTER TABLE TelefonoEmpleado ADD CONSTRAINT TelefonoEmpleado_fk0 FOREIGN KEY (Cedula) REFERENCES Empleado(Cedula);
ALTER TABLE TelefonoCliente ADD CONSTRAINT TelefonoCliente_fk0 FOREIGN KEY (Cedula) REFERENCES Cliente(Cedula);
ALTER TABLE CorreoCliente ADD CONSTRAINT CorreoCliente_fk0 FOREIGN KEY (Cedula) REFERENCES Cliente(Cedula);
ALTER TABLE Reservar ADD CONSTRAINT Reservar_fk0 FOREIGN KEY (Cedula) REFERENCES Cliente(Cedula);
ALTER TABLE Reservar ADD CONSTRAINT Reservar_fk1 FOREIGN KEY (NumeroHabitacion) REFERENCES Habitacion(NumeroHabitacion);
ALTER TABLE Solicitar ADD CONSTRAINT Solicitar_fk0 FOREIGN KEY (IdServicio) REFERENCES Servicio(IdServicio);
ALTER TABLE Solicitar ADD CONSTRAINT Solicitar_fk1 FOREIGN KEY (IdReserva) REFERENCES Reservar(IdReserva);
ALTER TABLE Solicitar ADD CONSTRAINT Solicitar_fk2 FOREIGN KEY (Cedula) REFERENCES Empleado(Cedula);


CREATE OR REPLACE FUNCTION verificar_solapamiento()
RETURNS TRIGGER AS $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM Reservar
        WHERE NumeroHabitacion = NEW.NumeroHabitacion
          AND IdReserva <> NEW.IdReserva
          AND fecha_rango && NEW.fecha_rango
    ) THEN
        RAISE EXCEPTION 
            'La habitación % ya tiene una reserva que se solapa con las fechas % - %',
            NEW.NumeroHabitacion, NEW.FechaLlegada, NEW.FechaSalida;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_no_solapamiento
BEFORE INSERT OR UPDATE ON Reservar
FOR EACH ROW
EXECUTE FUNCTION verificar_solapamiento();



CREATE OR REPLACE FUNCTION fn_audit_empleado()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        INSERT INTO Empleado_audit (operacion, usuario, cedula_empleado, dato_viejo, dato_nuevo)
        VALUES ('I', current_user, NEW.Cedula, NULL, row_to_json(NEW)::jsonb);

    ELSIF TG_OP = 'UPDATE' THEN
        INSERT INTO Empleado_audit (operacion, usuario, cedula_empleado, dato_viejo, dato_nuevo)
        VALUES ('U', current_user, OLD.Cedula, row_to_json(OLD)::jsonb, row_to_json(NEW)::jsonb);

    ELSIF TG_OP = 'DELETE' THEN
        INSERT INTO Empleado_audit (operacion, usuario, cedula_empleado, dato_viejo, dato_nuevo)
        VALUES ('D', current_user, OLD.Cedula, row_to_json(OLD)::jsonb, NULL);
    END IF;

    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- TRIGGER
CREATE TRIGGER trg_audit_empleado
AFTER INSERT OR UPDATE OR DELETE ON Empleado
FOR EACH ROW
EXECUTE FUNCTION fn_audit_empleado();


--Vista
CREATE VIEW Vista_Cliente_Reserva_Servicios AS
SELECT
    -- Cliente
    c.Cedula               AS CedulaCliente,
    c.PrimerNombre         AS NombreCliente,
    c.SegundoNombre        AS SegundoNombreCliente,
    c.PrimerApellido       AS ApellidoCliente,
    c.SegundoApellido      AS SegundoApellidoCliente,

    -- Reserva
    r.IdReserva,
    r.FechaLlegada,
    r.FechaSalida,
    r.TiempoCancelacion,
    r.NumeroHabitacion,

    -- Solicitud de servicio
    sol.Nombre             AS NombreSolicitud,
    sol.Fecha              AS FechaSolicitud,
    sol.Hora               AS HoraSolicitud,

    -- Servicio
    sv.IdServicio,
    sv.NombreServicio,
    sv.Descripcion         AS DescripcionServicio,
    sv.Costo               AS CostoServicio

FROM Cliente c
JOIN Reservar r
    ON c.Cedula = r.Cedula
JOIN Solicitar sol
    ON r.IdReserva = sol.IdReserva
JOIN Servicio sv
    ON sol.IdServicio = sv.IdServicio;



-- PRUEBAS

-- INSERT

INSERT INTO Area (NombreArea) VALUES ('aseo');

INSERT INTO Empleado 
    (Cedula, PrimerNombre, PrimerApellido, Calle, Carrera, Numero, Complemento, Cargo, Area, Salario)
VALUES 
    ('1234567890', 'Carlos', 'Gomez', 'Calle 10', 'Carrera 5', '20', 'Apto 301', 'Recepcionista', 1, 2000000);

-- UPDATE
UPDATE Empleado
SET Cargo = 'Supervisor', Salario = 2500000
WHERE Cedula = '1234567890';

-- DELETE
DELETE FROM Empleado
WHERE Cedula = '1234567890';

-- VERIFICAR
SELECT id, operacion, usuario, ts, cedula_empleado, dato_viejo, dato_nuevo
FROM Empleado_audit
ORDER BY id;


